name: Release build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2.0.0
      name: Checkout Code
     
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore DeltaQuestionEditor-WPF.sln
 
    - name: Build App
      run: msbuild DeltaQuestionEditor-WPF.sln /p:Configuration=Release /p:Platform=x64
 
#    Disabling this for now since the artifact storage limit is exceeded 
#    - name: Upload Artifact
#      uses: actions/upload-artifact@v1.0.0
#      with:
#        name: releases_x64
#        path: DeltaQuestionEditor-WPF\Releases
